add xdebug configuration

diff --git a/php-docker/php/Dockerfile b/php-docker/php/Dockerfile
--- a/php-docker/php/Dockerfile
+++ b/php-docker/php/Dockerfile
@@ -1,7 +1,14 @@
-FROM php:8.2-fpm-alpine
+FROM php:8.2-fpm-alpine as app
 
-RUN docker-php-ext-install pdo pdo_mysql
+# Useful PHP extension installer image, copy binary into your container
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
 
+# Install php extensions
+# exit on errors, exit on unset variables, print every command as it is executed
+RUN set -eux; \
+    install-php-extensions pdo pdo_mysql;
+
+#RUN docker-php-ext-install pdo pdo_mysql
 
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
@@ -14,3 +21,14 @@ RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-inte
 COPY ./app .
 
 RUN composer dump-autoload --optimize
+
+
+FROM app as app_dev
+
+ENV XDEBUG_MODE=off
+
+# Copy xdebug config file into container
+COPY ./php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
+
+RUN set -eux; \
+	install-php-extensions xdebug
